---
upstream_project_url: https://github.com/oconnor663/shared_thread.rs
upstream_package_name: shared_thread
downstream_package_name: rust-shared_thread

upstream_tag_template: v{version}

specfile_path: rust-shared_thread.spec

srpm_build_deps:
  - git
  - make

actions:
  # The last step here is required by Packit to return the archive name
  # https://packit.dev/docs/configuration/actions#create-archive
  create-archive:
    - bash -c "make sources"
    - bash -c "ls -1 *.crate | grep 'shared_thread'"

jobs:
  # Build RPMs for each pull request
  - job: copr_build
    trigger: pull_request
    owner: "r0x0d"
    project: shared_thread
    targets:
      - fedora-all

  # Build RPMs for main branch
  - job: copr_build
    trigger: commit
    branch: main
    owner: "r0x0d"
    project: shared_thread
    targets:
      - fedora-all
